# Generated by Django 4.1.1 on 2023-10-16 14:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(db_index=True, max_length=100, verbose_name='Category name')),
                ('category_slug', models.SlugField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ('category_name',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(db_index=True, max_length=255, verbose_name='Name')),
                ('product_slug', models.SlugField(max_length=255)),
                ('product_image', models.ImageField(blank=True, upload_to='images/product_imgs/', verbose_name='Image')),
                ('product_description', models.TextField(blank=True, verbose_name='Description')),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Price')),
                ('product_is_aviable', models.BooleanField(default=True, verbose_name='Availability')),
                ('product_created', models.DateTimeField(auto_now_add=True)),
                ('product_updated', models.DateTimeField(auto_now=True)),
                ('characteristics', models.JSONField(blank=True, default=dict)),
                ('product_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='webshop.category', verbose_name='Choose a category')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ('product_name',),
                'index_together': {('id', 'product_slug')},
            },
        ),
        migrations.CreateModel(
            name='ProductStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webshop.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Product Stock',
                'verbose_name_plural': 'Product Stocks',
            },
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchased_items', models.JSONField(default=dict, verbose_name='Purchased Items')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'User Info',
                'verbose_name_plural': 'Users Info',
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_name', models.CharField(db_index=True, max_length=100, verbose_name='Stock name')),
                ('stock_slug', models.SlugField(max_length=100, unique=True)),
                ('products', models.ManyToManyField(related_name='stocks', through='webshop.ProductStock', to='webshop.product', verbose_name='Products')),
            ],
            options={
                'verbose_name': 'Stock',
                'verbose_name_plural': 'Stocks',
                'ordering': ('stock_name',),
            },
        ),
        migrations.AddField(
            model_name='productstock',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webshop.stock', verbose_name='Stock'),
        ),
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=2048, verbose_name='Content')),
                ('is_recommend', models.BooleanField(default=True, verbose_name='Will you recommend?')),
                ('date_published', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Author')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='webshop.product', verbose_name='Choose a product')),
            ],
            options={
                'verbose_name': 'Review',
                'verbose_name_plural': 'Reviews',
                'ordering': ('date_published',),
            },
        ),
    ]
